version: '3.8'

services:
  app:
    image: mcr.microsoft.com/dotnet/aspnet:7.0 
    container_name: csharp-app
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5000:80"
    depends_on:
      - db 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=123shm321;Database=ElevatorService
    volumes:
      - .:/app
    networks:
      - app-network
      
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123shm321
      - POSTGRES_DB=ElevatorService 
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - app-network
      
volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
